// <auto-generated />
using System;
using APITeamsV3.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APITeamsV3.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CentralDbContext))]
    [Migration("20260402041707_AddPilotMode")]
    partial class AddPilotMode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("APITeamsV3.Domain.Entities.CompanyConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiScopes")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultChannelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FrontHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GraphClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GraphClientSecretRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GraphTenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPilotMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSyncTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeetingPolicyMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmartConnectionString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpaClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpaTenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiHost")
                        .IsUnique();

                    b.HasIndex("CompanyKey")
                        .IsUnique();

                    b.HasIndex("FrontHost")
                        .IsUnique();

                    b.ToTable("CompanyConfigs");
                });

            modelBuilder.Entity("APITeamsV3.Domain.Entities.CompanyPilotSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSeccion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyConfigId", "IdSeccion")
                        .IsUnique();

                    b.ToTable("CompanyPilotSections");
                });

            modelBuilder.Entity("APITeamsV3.Domain.Entities.CompanySede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSede")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyConfigId", "IdSede")
                        .IsUnique();

                    b.ToTable("CompanySedes");
                });

            modelBuilder.Entity("APITeamsV3.Domain.Entities.SyncJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HangfireJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("SyncJobs");
                });

            modelBuilder.Entity("APITeamsV3.Domain.Entities.SyncSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DaysOfWeek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Hour")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Minute")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncSchedules");
                });

            modelBuilder.Entity("APITeamsV3.Domain.Entities.CompanyPilotSection", b =>
                {
                    b.HasOne("APITeamsV3.Domain.Entities.CompanyConfig", null)
                        .WithMany("PilotSections")
                        .HasForeignKey("CompanyConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APITeamsV3.Domain.Entities.CompanyConfig", b =>
                {
                    b.Navigation("PilotSections");
                });
#pragma warning restore 612, 618
        }
    }
}
