// <auto-generated />
using System;
using APITeamsV3.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APITeamsV3.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CentralDbContext))]
    [Migration("20260212152220_AddSpaTenantId")]
    partial class AddSpaTenantId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("APITeamsV3.Domain.Entities.CompanyConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultChannelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FrontHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GraphClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GraphClientSecretRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GraphTenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSyncTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeetingPolicyMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmartConnectionString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpaClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpaTenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiHost")
                        .IsUnique();

                    b.HasIndex("CompanyKey")
                        .IsUnique();

                    b.HasIndex("FrontHost")
                        .IsUnique();

                    b.ToTable("CompanyConfigs");
                });

            modelBuilder.Entity("APITeamsV3.Domain.Entities.SyncJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
